### ISSUE TITLE
GitHub Actions status checks ignored

### ISSUE THREAD

**Issue by jack828** [microadam/exso#23]
release to staging
![image](https://user-images.githubusercontent.com/6363719/193636041-ed70557d-f8ec-476b-9dc2-7bb604bd840e.png)

adding to release
![image](https://user-images.githubusercontent.com/6363719/193636114-4e04d9dc-e24a-4f47-8707-5f74e91ffcee.png)

**Comment by jack828** [comment]
This is an issue with GitHub Actions not actually being a status check. I have added these to the CI workflows like so:

```      - uses: sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: pending
          context: Continuous Integration / GitHub Actions
          description: Running...
          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          sha: ${{github.event.pull_request.head.sha || github.sha}}
```
and at the end:

```

      - uses: sibz/github-status-action@v1
        if: always()
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: ${{ job.status }}
          context: Continuous Integration / GitHub Actions
          description: Finished
          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          sha: ${{github.event.pull_request.head.sha || github.sha}}

```
